# Generated by Django 3.0.8 on 2020-12-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incommingMsg', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('chatId', models.ForeignKey(db_column='chatId', on_delete=django.db.models.deletion.CASCADE, related_name='Image_Chat_Id', to='modelChat.Chat')),
            ],
        ),
    ]
