# Generated by Django 3.0.8 on 2020-12-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelChat', '0002_auto_20201209_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='chatId',
            field=models.ForeignKey(db_column='chatId', on_delete=django.db.models.deletion.CASCADE, related_name='chatId', to='modelChat.Chat'),
        ),
    ]
