# Generated by Django 3.0.8 on 2020-12-07 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingMsg', models.CharField(max_length=500)),
                ('reply', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
